import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    
      <h2> Featured Products</h2>
      <p>...</p>
    </>
  )
}
