export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <header style={{background:'#f4f4f4', height:'50px'}}>logo</header>
        {children}
        <footer style={{background:'#f4f4f4', height:'30px', position:'relative', bottom:'0'}}>Footer goes here</footer>
      </body>
    </html>
  )
}
